package hcmute.puzzle.exception;

public enum ErrorCode {
	ALREADY_EXISTS_ERROR("ALREADY_EXISTS_ERROR"),
	BAD_REQUEST_ERROR("BAD_REQUEST_ERROR"),
	INVALID_ERROR("INVALID_ERROR"),
	AUTHENTICATION_ERROR("AUTHENTICATION_ERROR"),
	UNAUTHORIZED_ERROR("UNAUTHORIZED_ERROR"),
	FILE_STORAGE_ERROR("FILE_STORAGE_ERROR"),
	INVALID_DATA_ERROR("INVALID_DATA_ERROR"),
	MISSING_PARAM_ERROR("MISSING_PARAM_ERROR"),
	NOT_FOUND_DATA_ERROR("NOT_FOUND_DATA_ERROR"),
	NOT_FOUND_ERROR("NOT_FOUND_ERROR"),
	PARTIAL_FAILURE_ERROR("PARTIAL_FAILURE_ERROR"),
	SERVER_ERROR("SERVER_ERROR"),
	CLIENT_ERROR("CLIENT_ERROR"),
	UPLOAD_FAILURE_ERROR("UPLOAD_FAILURE_ERROR"),
	VALIDATION_ERROR("VALIDATION_ERROR");


	private String value;
	ErrorCode(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}
}
